### ISSUE TITLE
how to ignore locale?

### ISSUE THREAD

**Issue by 0910** [apeacox/panoramic#20]
Hi, first at all thanks for this gem.
Im storing a diferent template for each view, but i dont want to specify the locale.
I have made 2 tests:
1)  removed the field from the form -> template is not saved.
2)  leave the field blank -> "error (not in the list)"

any ideas?

**Comment by apeacox** [comment]
Hi @0910

according to this spec, templates without locales should be saved because valid. Btw, I'm releasing a (long awaited) update for this gem, v0.0.6. Try it and let me know :-)
